name: HDU-Library-Master
on:
  schedule:
    - cron: '25 11 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Check config
        env:
          HLMUSERID: ${{ secrets.HLMUSERID }}
          HLMPASSWORD: ${{ secrets.HLMPASSWORD }}
          HLMPLANCODE: ${{ vars.HLMPLANCODE }}
          HLMMAXTRIALS: ${{ vars.HLMMAXTRIALS }}
          HLMDELAY: ${{ vars.HLMDELAY }}
          HLMLOGDETAILS: ${{ vars.HLMLOGDETAILS }}
          HLMEXECUTETIME: ${{ vars.HLMEXECUTETIME }}
          HLMPREEXETIME: ${{ vars.HLMPREEXETIME }}
        run: python main.py > result.log
      - name: Seats reserving
        env:
          HLMUSERID: ${{ secrets.HLMUSERID }}
          HLMPASSWORD: ${{ secrets.HLMPASSWORD }}
          HLMPLANCODE: ${{ vars.HLMPLANCODE }}
          HLMMAXTRIALS: ${{ vars.HLMMAXTRIALS }}
          HLMDELAY: ${{ vars.HLMDELAY }}
          HLMLOGDETAILS: ${{ vars.HLMLOGDETAILS }}
          HLMEXECUTETIME: ${{ vars.HLMEXECUTETIME }}
          HLMPREEXETIME: ${{ vars.HLMPREEXETIME }}
        run: python main.py >> result.log
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          serveraddress: smtp.163.com
          serverport: 465
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: 'HDU Library Seat Reservation Result'
          body: file://result.log
          to: yifeng.ruan@gmail.com
          from: GitHub Actions
          content_type: text/plain
