name: HDU-Library-Master
on:
  schedule:
    - cron: '45 11 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Check config
        env:
          HLMUSERID: ${{ secrets.HLMUSERID }}
          HLMPASSWORD: ${{ secrets.HLMPASSWORD }}
          HLMPLANCODE: ${{ vars.HLMPLANCODE }}
          HLMMAXTRIALS: ${{ vars.HLMMAXTRIALS }}
          HLMDELAY: ${{ vars.HLMDELAY }}
          HLMLOGDETAILS: ${{ vars.HLMLOGDETAILS }}
          HLMEXECUTETIME: ${{ vars.HLMEXECUTETIME }}
          HLMPREEXETIME: ${{ vars.HLMPREEXETIME }}
        run: python main.py
      - name: Seats reserving
        env:
          HLMUSERID: ${{ secrets.HLMUSERID }}
          HLMPASSWORD: ${{ secrets.HLMPASSWORD }}
          HLMPLANCODE: ${{ vars.HLMPLANCODE }}
          HLMMAXTRIALS: ${{ vars.HLMMAXTRIALS }}
          HLMDELAY: ${{ vars.HLMDELAY }}
          HLMLOGDETAILS: ${{ vars.HLMLOGDETAILS }}
          HLMEXECUTETIME: ${{ vars.HLMEXECUTETIME }}
          HLMPREEXETIME: ${{ vars.HLMPREEXETIME }}
        run: python main.py > result.log
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: 'HDU图书馆座位预约结果'
          body: file://result.log
          to: zhenglei.y@hdu.edu.cn
          from: GitHub Actions
